version: '3.9'

services:
    beer-tap-api:
        container_name: beer-tap-api
        image: maven:3.8.5-openjdk-17
        depends_on:
            - rv-postgres-db
        volumes:
            - "${PWD}:/home/maven/project"
            - "rv-maven-cache:/root/.m2"
        working_dir: "/home/maven/project"
        ports:
            - "8080:8080"
        networks:
            internal-net:

    rv-postgres-db:
        container_name: rv-postgres-db
        image: postgres:13.4-alpine
        restart: on-failure
        volumes:
            - rv-volume:/var/lib/postgresql/data
        env_file:
            - postgres.dev.env
        ports:
            - "15432:5432"
        networks:
            internal-net:

volumes:
    rv-volume:
    rv-maven-cache:

networks:
    internal-net:
        name: rv-net
